#ifndef RESOURCE_VERSION_H
#define RESOURCE_VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 5
#define VERSION_PATCH 0
#define VERSION_REVISION 0

#define APP_NAME "Re-search for Internet Explorer"
#define APP_COMPANY "Semcon Sweden AB"
#define APP_COPYRIGHT "Copyright (c) 2016"

#define RES_STR2(x) #x
#define RES_STR(x) RES_STR2(x)

#define RESOURCE_FILEVERSION VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_REVISION
#define RESOURCE_PRODUCTVERSION VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH

#define RESOURCE_FILEVERSION_STRING RES_STR(VERSION_MAJOR) "." RES_STR(VERSION_MINOR) "." RES_STR(VERSION_PATCH) "." RES_STR(VERSION_REVISION)
#define RESOURCE_PRODUCTVERSION_STRING RES_STR(VERSION_MAJOR) "." RES_STR(VERSION_MINOR) "." RES_STR(VERSION_PATCH)

// Nasty stringification macros to generate strings for about box
#define ABOUT_GEN_VERSION_STRING_X(a, b, c) v##a##.##b##.##c
#define ABOUT_GEN_VERSION_STRING(a, b, c) RES_STR(ABOUT_GEN_VERSION_STRING_X(a, b, c))

#define APP_ABOUT_FULL_VERSION_STRING ABOUT_GEN_VERSION_STRING(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH))

#endif
